spring:
  profiles: dev

# Eureka (Discovery)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10

# Logging
logging:
  level:
    root: INFO
    com.example: DEBUG

# Common datasource defaults (can be overridden per service)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/common_db
    username: root
    password: root

# RabbitMQ
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
