spring:
  application:
    name: auth-service
  profiles: dev

server:
  port: 9001

# Auth service uses its own database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root

# JWT settings
security:
  jwt:
    secret: 1e82e7a9c156dcb66bd00500a11d5d6c
    expiration: 3600000  # 1 hour in ms
